available:
  channels:
  - CommandChannelController
  - NeighbourChannelController
  communication:
  - UDP
  - LocalUDP
  controllers:
  - FlockController
  digestions:
  - NONE
  - BYTES
  evaluators: []
  flight:
  - FlightlessFlightController
  sensors: []
  unknown: []
configuration:
  CommandChannelController:
    commInterface: '*'
    interval: 1.0
  FlightlessFlightController:
    interval: 1.0
  FlockController:
    PositionTolerance: 1.0
    UAVMaxSpeed: 2.0
    filterSimilarity: true
    flightStep: 10.0
    flockArea: 200.0
    flockDistance: 8.6
    flockGroup: 1
    flockHysteresis: 0.0
    flockMaxDistance: 12.2
    flockMinDistance: 5.0
    interval: 1.0
    membersFilter: true
    membersLimit: 2
    ownVelocityWeight: 0.5
    potFieldWidth: 20.0
    similarityThreshold: 25
  LocalUDP:
    digestion: NONE
    interval: 1.0
    mediator-port: 1337
    own-port: 1338
  NeighbourChannelController:
    commInterface: '*'
    interval: 1.0
  UDP:
    broadcast-address: 255.255.255.255
    digestion: NONE
    interval: 1.0
    p2p: false
    port: 1337
    target-address: 255.255.255.255
drone:
  descriptor: ''
  home: (0.0, 0.0)
  id: -1
mission: mission.yml
modules:
  channels: []
  communication: []
  controllers: []
  evaluators: []
  flight: FlightlessFlightController
  sensors: []
  unknown: []
