available:
  channels:
  - CommandChannelController
  - NeighbourChannelController
  communication:
  - BroadUDP
  - P2PUDP
  - LocalUDP
  controllers:
  - FlockController
  digestions:
  - NONE
  - BYTES
  evaluators:
  - AirSimEvaluator
  flight:
  - FlightlessFlightController
  - AirSimFlightController
  sensors:
  - AirSimSensors
  unknown: []
configuration: {}
drone:
  descriptor: ''
  home: (0.0, 0.0)
  id: -1
mission: mission.yml
modules:
  channels: []
  communication: []
  controllers: []
  evaluators: []
  flight: FlightlessFlightController
  sensors: []
  unknown: []
