available:
  channels:
  - CommandChannelController
  - NeighbourChannelController
  communication:
  - BroadUDP
  - P2PUDP
  - LocalUDP
  controllers:
  - FlockController
  digestions:
  - NONE
  - BYTES
  evaluators:
  - AirSimEvaluator
  flight:
  - FlightlessFlightController
  - AirSimFlightController
  sensors:
  - AirSimSensors
  unknown: []
configuration:
  AirSimFlightController:
    autoLaunchAirsim: false
    environmentConfig:
      airsimBinaryPath: ''
      defineConfigHere: false
      resolution:
      - 1280
      - 720
      viewMode: FlyWithMe
      wind:
      - 0
      - 0
      - 0
    forceCloseAirsimOnExit: false
    home:
      X: 0
      Y: 0
      Z: 0
    ip: ''
    name: UAV1
    port: 41451
    sensorFrequency: 0.5
    timeoutValue: 3600000
    useEnvironmentHome: true
  AirSimSensors:
    interval: 1.0
  BroadUDP:
    digestion: NONE
    port: 1337
    target-address: 255.255.255.255
  CommandChannelController:
    commInterface: '*'
    interval: 1.0
  FlockController:
    PositionTolerance: 1.0
    UAVMaxSpeed: 2.0
    filterSimilarity: true
    flightStep: 10.0
    flockArea: 200.0
    flockDistance: 8.6
    flockGroup: 0
    flockHysteresis: 0.0
    flockMaxDistance: 12.2
    flockMinDistance: 5.0
    membersFilter: true
    membersLimit: 2
    ownVelocityWeight: 0.5
    potFieldWidth: 20.0
    similarityThreshold: 25
  LocalUDP:
    digestion: NONE
    mediator-port: 1337
    port: 1338
  NeighbourChannelController:
    commInterface: '*'
    interval: 1.0
  P2PUDP:
    digestion: NONE
    port: 1337
    target-address: 255.255.255.255
drone:
  descriptor: UAV1
  home: (0.0, 0.0)
  id: 1
mission: mission.yml
modules:
  channels:
  - NeighbourChannelController
  communication:
  - LocalUDP
  controllers:
  - FlockController
  evaluators: []
  flight: FlightlessFlightController
  sensors: []
  unknown: []
